# Generated by Django 4.2 on 2023-12-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='Start time of the booking.')),
                ('end_time', models.DateTimeField(help_text='End time of the booking.')),
                ('no_of_persons', models.PositiveIntegerField(help_text='Number of persons for the booking.')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(help_text='Name of the meeting room.', max_length=255)),
                ('capacity', models.PositiveIntegerField(help_text='Capacity of the meeting room.')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the meeting room is active or not.')),
            ],
        ),
    ]
