# Generated by Django 4.2 on 2023-12-10 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghistory',
            name='booked_by',
            field=models.ForeignKey(help_text='User making the booking.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='meeting_room',
            field=models.ForeignKey(help_text='Meeting room associated with the booking.', on_delete=django.db.models.deletion.CASCADE, related_name='booking_histories', to='booking.meetingroom'),
        ),
        migrations.AddIndex(
            model_name='bookinghistory',
            index=models.Index(fields=['meeting_room', 'start_time', 'end_time'], name='booking_boo_meeting_d800f0_idx'),
        ),
    ]
